gedlib: GM Class Reference
GM Class Reference
Public Member Functions
GM (const arma::mat &data)
GM (const arma::vec &mu, const arma::mat &sigma)
unsigned int const & getD () const
arma::rowvec getDataProb (const arma::mat &data) const
arma::vec const & getMu () const
double getProb (const arma::vec &loc) const
arma::mat const & getSigma () const
void print (std::string header="") const
bool sanityCheck () const
void setMu (const arma::vec &mu)
void setSigma (const arma::mat &sigma)
Private Attributes
double coeff_
unsigned int D_
arma::mat invSigma_
arma::vec mu_
arma::mat sigma_
Detailed Description
A class to represent a gaussian model, using armadillo matrices.
Definition at line 18 of file gmm.hpp.
Member Function Documentation
arma::rowvec getDataProb (const arma::mat & data) const
For optimization reasons (to use vector multiplication), return the probability of a set of column-vectors
Definition at line 47 of file gmm.hpp.
References coeff_, exp(), and sum().
double getProb (const arma::vec & loc) const
Probability for a single vector
Definition at line 40 of file gmm.hpp.
References coeff_, and exp().
bool sanityCheck () const
For debugging reasons
Definition at line 83 of file gmm.hpp.
References coeff_, std::cout, and std::endl().
Member Data Documentation
double coeff_ [private]
The coeff is cached and recalculated on a sigma change
Definition at line 26 of file gmm.hpp.
Referenced by getDataProb(), getProb(), and sanityCheck().
The documentation for this class was generated from the following file:
gmm.hpp