gedlib: GMM Class Reference
GMM Class Reference
Public Member Functions
GMM (const arma::mat &data, unsigned int kmin, unsigned int kmax)
arma::uvec cleanupGMs ()
void findMaxLikelihood (const arma::mat &data, unsigned int kmin, unsigned int kmax)
unsigned int getD () const
GM const & getGM (unsigned int index) const
arma::vec getMu () const
size_t getNumComponents ()
double getProb (const arma::vec &datum, unsigned int start, unsigned int end) const
double getProb (const arma::vec &datum, unsigned int index) const
double getProb (const arma::vec &datum) const
arma::vec const & getWeights () const
std::vector< GM > initMixtureModel (const arma::mat &data, unsigned int kmax)
unsigned int n_gm () const
void normalizeWeights ()
void print (std::string header="") const
void setGM (unsigned int index, const GM &gm)
bool updateGM (unsigned int index, double weight, const arma::vec &mu, const arma::mat &sigma)
Private Attributes
unsigned int D_
std::vector< GM > mixture_
arma::vec weights_
Detailed Description
Models a Gaussian mixture model.
Definition at line 107 of file gmm.hpp.
Member Function Documentation
arma::uvec cleanupGMs ()
Removes any Gaussian models whose correspondent weight is zero or less
Definition at line 140 of file gmm.hpp.
References vector< _Tp, _Alloc >::begin(), std::distance(), vector< _Tp, _Alloc >::erase(), and find().
void findMaxLikelihood (const arma::mat & data, unsigned int kmin, unsigned int kmax)
Find the best Gaussian mixture model for given data, via the EM-algorithm.
Parameters:
[in] data The data that the model should be fitted to
[in] kmin the minimum number of Gaussian models that should be used
[in] kmax the maximum number (and therefore starting number) of Gaussian models that should be used
See also:
"Unsupervised learning of finite mixture models", M. Figueiredo and A. K. Jain, http://www.lx.it.pt/~mtf/IEEE_TPAMI_2002.pdf
Definition at line 222 of file gmm.hpp.
References std::abs(), vector< _Tp, _Alloc >::begin(), std::cout, vector< _Tp, _Alloc >::erase(), find(), initMixtureModel(), log(), max(), min(), vector< _Tp, _Alloc >::size(), and sum().
double getProb (const arma::vec & datum, unsigned int start, unsigned int end) const
Return the probability of a vector, given the current mixture model. Only takes the models in [start, end) into account.
Definition at line 197 of file gmm.hpp.
Referenced by HMMComp::expUnscentedTransform().
std::vector<GM> initMixtureModel (const arma::mat & data, unsigned int kmax)
Initialize the Mixture model by picking a random subset of the data which will become the means for every Gaussian model.
Definition at line 366 of file gmm.hpp.
Referenced by findMaxLikelihood().
The documentation for this class was generated from the following file:
gmm.hpp