gedlib: HMMComp Class Reference
HMMComp Class Reference
Static Public Member Functions
static double expUnscentedTransform (const GMM &gmm1, const GMM &gmm2, double K=0.5)
static arma::rowvec findStationary (const arma::mat &A, unsigned int steps=1000, double eps=1E-2)
static arma::cube findTransformationCube (const HMM &hmm1, const HMM &hmm2)
static arma::mat findTransformationMatrix (const HMM &hmm1, const HMM &hmm2)
static double giniIndex (const arma::vec &u)
static double gmDistance (const GM &gm1, const GM &gm2)
static double gmmDistance (const GMM &gmm1, const GMM &gmm2)
static double hoyerMeasure (const arma::vec &u)
static double kld (const HMM &hmm1, const HMM &hmm2)
static double normalizedGiniIndex (const arma::vec &u)
static double pmfDistance (const arma::mat &v1, const arma::mat &v2)
static arma::mat samplePointOffsets (const arma::mat &M)
template<typename TransformationFunctor = IdentityFunctor>
static double sMrandomWalk (const HMM &hmm1, const HMM &hmm2, TransformationFunctor func=TransformationFunctor(), int distanceSelect=0)
static double symmetric_kld (const HMM &hmm1, const HMM &hmm2)
Detailed Description
A class to calculate similarities/distances between Hidden Markov Models.
Definition at line 13 of file kld.hpp.
Member Function Documentation
static double expUnscentedTransform (const GMM & gmm1, const GMM & gmm2, double K = 0.5) [static]
Based on an algorithm described in
See also:
"An Efficient Image Similarity Measure based on Approximations of KL-Divergence Between Two Gaussian Mixtures", by Goldberger, Gordon, Greenspan While the algorithm normally calculates the Kullback-Leibler distance KL(f||g) which features logarithms, we aren't interested in the distance itself but rather in exp(-KL(f||g)), which enables slight changes to their original algorithm to prevent infinite distances.
Returns:
The similarity between two GMMs, in [0,1]
Definition at line 194 of file kld.hpp.
References GMM::getProb(), pow(), and samplePointOffsets().
Referenced by sMrandomWalk().
static arma::rowvec findStationary (const arma::mat & A, unsigned int steps = 1000, double eps = 1E-2) [static]
Assuming that the Hidden Markov Model has underlying stationary probabilities, find pi with pi * A = pi;.
findStationary
Parameters:
[in] A Matrix with transition probabilities
Returns:
pi stationary probability vector
Definition at line 22 of file kld.hpp.
References norm().
Referenced by findTransformationCube(), findTransformationMatrix(), and sMrandomWalk().
static arma::cube findTransformationCube (const HMM & hmm1, const HMM & hmm2) [static]
Assuming that there exists a linear transformation between the underlying data of hmm1 and hmm2, try to reverse-engineer it. This method picks the center of masses of the most probable states (
See also:
findStationary) for both HMMs, returning a Transformation Matrix for every match-permutation. For a 3d-problem, this for example requires 3 points for both HMMs, resulting in 6 different matches. The method works well in reversing rotations, mirroring and similar operations.
Returns:
TransformationMatrices, packed in an armadillo cube. Every slice is one possible transformation, the most probable is returnval.slice(0)
Definition at line 89 of file kld.hpp.
References HMM::A_, HMM::BModels_, std::cout, std::endl(), findStationary(), and std::next_permutation().
static arma::mat findTransformationMatrix (const HMM & hmm1, const HMM & hmm2) [static]
Assuming that there exists a linear transformation between the underlying data of hmm1 and hmm2, try to reverse-engineer it. This method picks the most probable states (according to their stationary probability
See also:
findStationary), and calculates the coordinate transformation necessary to align their most important sigmas. This is likely a very crude guess to the transformation and thus not recommended.
Definition at line 47 of file kld.hpp.
References HMM::A_, HMM::BModels_, findStationary(), and sqrt().
static double giniIndex (const arma::vec & u) [static]
One of the Measures for the sparsity of a vector
Definition at line 227 of file kld.hpp.
References norm(), and sum().
Referenced by normalizedGiniIndex().
static double hoyerMeasure (const arma::vec & u) [static]
One of the Measures for the sparsity of a vector
Definition at line 219 of file kld.hpp.
References norm(), and std::sqrt().
static double normalizedGiniIndex (const arma::vec & u) [static]
One of the Measures for the sparsity of a vector
Definition at line 245 of file kld.hpp.
References giniIndex(), if(), and norm().
Referenced by sMrandomWalk().
static arma::mat samplePointOffsets (const arma::mat & M) [static]
Helper Function for the Unscented Transform,
See also:
"An Efficient Image Similarity Measure based on Approximations of KL-Divergence Between Two Gaussian Mixtures", by Goldberger, Gordon, Greenspan
Definition at line 167 of file kld.hpp.
References sqrt().
Referenced by expUnscentedTransform().
static double sMrandomWalk (const HMM & hmm1, const HMM & hmm2, TransformationFunctor func = TransformationFunctor(), int distanceSelect = 0) [static]
Based on
See also:
"A Novel Low-Complexity HMM Similarity Measure", by Sahraeian, Yoon
Slight changes were made to create more representative results, as the quality of the matches between states was also taken into account instead of just the sparsity of the matching matrix.
Definition at line 264 of file kld.hpp.
References HMM::A_, HMM::BModels_, exp(), expUnscentedTransform(), findStationary(), max(), HMM::N_, and normalizedGiniIndex().
The documentation for this class was generated from the following file:
kld.hpp